# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' aaa
#' 
#' ...
#' 
#' \deqn{ v_p(f) = \sup \left\{ \sum_{i=1}^m |f(t_i) -
#' f(t_{i-1})|^p : 0=t_0<t_1<\dots<t_m=1 \right\} }{ v_p(f) =
#' sup { \sum |f(t_i) - f(t_{i-1})|^p : 0=t_0<t_1<\dots<t_m=1}
#' }
#' 
#' @return The vector of index of change points.
#' @param RMat \code{numeric} vector.
#' @param resize \code{numeric} vector.
#' @export
aperm2cv <- function(RMat, resize = TRUE) {
    .Call('opencv_aperm2cv', PACKAGE = 'opencv', RMat, resize)
}

test_cv1 <- function(RMat, show = TRUE) {
    .Call('opencv_test_cv1', PACKAGE = 'opencv', RMat, show)
}

test_cv2 <- function(RMat) {
    .Call('opencv_test_cv2', PACKAGE = 'opencv', RMat)
}

test_cv3 <- function() {
    .Call('opencv_test_cv3', PACKAGE = 'opencv')
}

#' aaa
#' 
#' ...
#' 
#' asa
#' 
#' @return The vector of index of change points.
#' @param RMat \code{numeric} vector.
#' @param threshold \code{numeric} vector.
#' @export
thinning <- function(RMat, threshold = 10) {
    .Call('opencv_thinningFromR', PACKAGE = 'opencv', RMat, threshold)
}

#' Linear 2d filter from opencv
#' 
#' ...
#' 
#' \code{method=0}(SQDIFF)
#' \deqn{ R(x, y) = \sum (T(x', y') - I(x+x', y+y'))^2  }
#' 
#' \code{method=1}(SQDIFF_NORMED)
#' \deqn{ R(x, y) = \sum (T(x', y') - I(x+x', y+y'))^2 / \sqrt{\sum (T(x', y')^2 \sum I(x+x', y+y')^2 }}  
#' 
#' \code{method=2}(CCORR)
#' \deqn{ R(x, y) = \sum T(x', y')I(x+x', y+y')  }
#' 
#' \code{method=3}(CCORR_NORMED)
#' \deqn{ R(x, y) = \sum T(x', y')I(x+x', y+y') / \sqrt{\sum (T(x', y')^2 \sum I(x+x', y+y')^2 }}
#' 
#' \code{method=4}(CCOEFF)
#' \deqn{ R(x, y) = \sum T'(x', y')I'(x+x', y+y')  }
#' 
#' \code{method=5}(CCOEFF_NORMED)
#' \deqn{ R(x, y) = \sum T'(x', y')I'(x+x', y+y') / \sqrt{\sum (T'(x', y')^2 \sum I'(x+x', y+y')^2 }}
#' 
#' where 
#' \deqn{ T' = T - mean(T)} 
#' \deqn{ I'(x,y) = I(x,y) - mean(I, by=(x', y'))}
#' 
#' 
#' @return The vector of index of change points.
#' @param image \code{numeric} vector.
#' @param templ \code{numeric} vector.
#' @param method \code{numeric} vector.
#' @export
matchTemplate_cv <- function(image, templ, method = 0L) {
    .Call('opencv_matchTemplate_cv', PACKAGE = 'opencv', image, templ, method)
}

#' Linear 2d filter from opencv
#' 
#' ...
#' 
#' ...
#' 
#' @return The vector of index of change points.
#' @param image \code{numeric} vector.
#' @param kernel \code{numeric} vector.
#' @param anchor \code{numeric} vector.
#' @param delta \code{numeric} vector.
#' @export
filter2D_cv <- function(image, kernel, anchor, delta = 0) {
    .Call('opencv_filter2D_cv', PACKAGE = 'opencv', image, kernel, anchor, delta)
}

#' General form of 2d filter
#' 
#' ...
#' 
#' Gener form filter. Returns matrix \code{res} with values \code{res[i,j] = sum((A[si, sj] - D)^p)}.
#' 
#' @return The vector of index of change points.
#' @param A \code{numeric} vector.
#' @param D \code{numeric} vector.
#' @param K \code{numeric} vector.
#' @param p \code{numeric} vector.
#' @export
GFiler2D_bf <- function(A, D, K, p = 1) {
    .Call('opencv_GFiler2D_bf', PACKAGE = 'opencv', A, D, K, p)
}

